### ISSUE TITLE
Does not compile on rustc 1.81.0

### ISSUE THREAD

**Issue by TheAlexDev23** [TheAlexDev23/power-options#6]
Some users report power-options not compiling with rustc version 1.81.0

```
error[E0716]: temporary value dropped while borrowed
   --> crates/power-daemon/src/profile.rs:548:18
    |
546 |         let firmware_parameters = if let Some(power_scheme) = self.power_scheme {
    |             ------------------- borrow later stored here
547 |             if uses_iwlmvm {
548 |                 &format!("power_scheme={}", power_scheme)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ creates a temporary value which is freed while still in use
549 |             } else if power_scheme == 3 {
    |             - temporary value is freed at the end of this statement
    |
    = note: consider using a `let` binding to create a longer lived value
    = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0716`.
```

The fix should be really trivial but it's weird that it happens.
